### ISSUE TITLE
`InvalidOperationException` when assembling `JMP r/m64`

### ISSUE THREAD

**Issue by alexrp** [icedland/iced#310] opened 2022-07-11 23:27 UTC
```csharp
using Iced.Intel;
using static Iced.Intel.AssemblerRegisters;

var asm = new Assembler(64);

using var stream = new MemoryStream();
var writer = new StreamCodeWriter(stream);

asm.jmp(__qword_ptr[0xaabbccddeeffaabb]);

_ = asm.Assemble(writer, 0);

Console.WriteLine(Convert.ToHexString(stream.ToArray()).ToLowerInvariant());
```

This throws:

```
Unhandled exception. System.InvalidOperationException: Operand 0: Displacement must fit in an int : 0x0 jmp qword ptr [0AABBCCDDEEFFAABBh]
   at Iced.Intel.Assembler.Assemble(CodeWriter writer, UInt64 rip, BlockEncoderOptions options)
   at Program.<Main>$(String[] args) in C:\Users\alex\source\repos\tests\Program.cs:line 12
```

This seems odd to me. I would expect this to successfully assemble to a `JMP r/m64`: https://www.felixcloutier.com/x86/jmp

But it's quite possible I'm missing something, because some other tools also handle this particular instruction weirdly. For example, Binary Ninja's x86-64 assembler turns `jmp qword [0xaabbccddeeffaabb]` into `ff 24 25 bb aa ff ee`...

**Comment by wtfsck** [comment] 2022-07-12 04:23
Looks like a dupe of https://github.com/icedland/iced/issues/212

**Comment by alexrp** [comment] 2022-07-12 07:00
Actually, I think this issue is just invalid altogether.

I was under the impression that the `FF /4 JMP r/m64` encoding would allow a full 64-bit memory address from which to load the jump address from, but that doesn't seem to be the case? I might have been confusing it with `REX.W FF /5 JMP m16:64`...

**Comment by wtfsck** [comment] 2022-07-12 18:09
`jmp qword ptr [mem]` reads a 64-bit value from memory (address 'mem') and treats the value as an address in memory and jumps to it. It doesn't jump to the address value of 'mem'.

`jmp qword ptr [1234]` => target = readmem(1234); set rip = target; execute code from current rip.

If you want to jump to the address `0xaabbccddeeffaabb`, you can just do `mov rax,0xaabbccddeeffaabb; jmp rax`

**Closed** 2022-07-12 18:52 UTC
