### ISSUE TITLE
Using Box::into_raw has resulted in numerous memory leak issues

### ISSUE THREAD

**Issue by persytry** [icedland/iced#552] opened 2024-04-26 06:43 UTC
![image](https://github.com/icedland/iced/assets/88146305/f30f91e1-5c6e-4d99-b4b5-e30f09037585)
![image](https://github.com/icedland/iced/assets/88146305/d619296c-3b1a-47b5-87f8-2fed06372bc4)
There are numerous instances where the `Box::into_raw` method is being used, which can lead to memory leaks. For example, within the `box_opcode_handler` function, `Box::into_raw` is employed, returning a `*const OpCodeHandler`. This specific usage results in a memory leak. Given that the `box_opcode_handler` function is called from many locations throughout the codebase, it follows that iced-x86 suffers from severe memory leak problems. We kindly request that you address and rectify these issues. Thank you.

**Comment by wtfsck** [comment] 2024-04-26 07:59
I think this has been fixed already if you try the latest master.

**Comment by persytry** [comment] 2024-04-27 07:30
I use the iced-x86 version "1.21.0", and also git clone the lastest master of iced, both has the leaks issues. 
You should look the function `box_opcode_handler`(iced/src/rust/iced-x86/src/decoder/table_de/mod.rs):
```rust
fn box_opcode_handler<T>((decode, handler): (OpCodeHandlerDecodeFn, T)) -> (OpCodeHandlerDecodeFn, *const OpCodeHandler) {
	// All handlers are #[repr(C)] and the first fields are the same as OpCodeHandler
	(decode, Box::into_raw(Box::new(handler)) as *const OpCodeHandler)
}
```
The usage is wrong above: `Box::into_raw(Box::new(handler)) as *const OpCodeHandler`. Can not be used like that, it causes leaks.
If you use the function `Box::into_raw" , you must use `Box::from_raw` also, or else would be leaks.
Please fix it, iced-x86 has many leaks like that.

**Comment by persytry** [comment] 2024-04-27 07:39
> I think this has been fixed already if you try the latest master.
> 
> They're all stored in lazy_statics.

The results of function `box_opcode_handler`, has not stored in lazy_statics

**Comment by wtfsck** [comment] 2024-04-27 08:17
Show how to reproduce this because this has already been talked about in #524

> The results of function box_opcode_handler, has not stored in lazy_statics

They're reachable from lazy statics.

**Comment by persytry** [comment] 2024-04-28 01:55
This is my Cargo.toml:
![image](https://github.com/icedland/iced/assets/88146305/dc520578-af44-43ed-a92d-2b4fb05c2834)
I used the lastest master, and has the leaks too.
I found two cases cause leaks:
1. use `Box::into_raw`, but not use `Box::from_raw` to free the memory.
2. usage of `lazy_static` is wrong, because iced-x86 not support function to free memories stored in `lazy_static`, [look this article](https://users.rust-lang.org/t/how-to-free-a-lazy-static-mem-leak/11194).

iced-x86 should support some functions to free all memories which allocated by iced-x86, example allocated by `Box::into_raw` and `lazy_static`.
I develop windows driver(kernel module) program, I must control all memory malloc and free by mannual, so iced-x86 should support it.
Thanks.

**Comment by wtfsck** [comment] 2024-04-28 04:54
Memory allocated by lazy statics are supposed to last the whole program execution and thus they get freed when the program exits.

> use Box::into_raw, but not use Box::from_raw to free the memory.

Because they're lazy statics and they're not meant to be freed.

> usage of lazy_static is wrong, because iced-x86 not support function to free memories stored in lazy_static by manual, [look this article](https://users.rust-lang.org/t/how-to-free-a-lazy-static-mem-leak/11194).

It's not wrong because I don't use a feature to free lazy static memory. They're supposed to be there the whole time the program is executed.

I do have plans to remove the lazy static dependency in a future version though.

Do you have a repro of the memory leak or do you consider it to be a memory leak because I use lazy statics that are freed on program exit?

**Comment by persytry** [comment] 2024-04-29 02:00
> Memory allocated by lazy statics are supposed to last the whole program execution and thus they get freed when the program exits.

You said the `whole program` only means "the user mode program", which run system ring-3 level. `lazy_static` could freed memory at ring-3 program, because it depend on CRT runtime. But CRT runtime only works on ring-3 level program, not work in kernel model program. So `lazy_static` will not free memory automatically at ring-0 kernel mode program.
iced-x86 support `no_std`, the ring-0 kernel mode program(e.g. windows .sys file, the driver program) only could run at `no_std` environment. And `no_std` environment has not CRT runtime.
A driver programe like a `dll`, which all can be load and unload. My Driver use iced-x86 at loading time, when I unload my driver, I free iced-x86 and free all memory by manually, because `lazy_static` can not free automatically, it is not like user mode program. That is determined by windows system mechanism, user mode programe runtime mode is not same as kernel mode program.

**Comment by persytry** [comment] 2024-04-29 02:14
Enven if iced-x86 only run at user mode program, your `Box::into_raw` and `lazy_static` usage is wrong.
First, iced-x86 should not use `lazy_static`, should not stored memories in `lazy_static` which has whole program life time, it's not reasonable. I maybe use iced-x86 once at my user mode program, but it use memory last whole program life time. I maybe use iced-x86 many times at my user mode program, I would found my memory is keeping growing.
Second, `lazy_static` only free memory it maintains itself, would not free the memories allocated by `Box::new`.

**Comment by persytry** [comment] 2024-04-29 02:22
1. I suggest you remove the `lazy_static` dependency, otherwise iced-x86 could not support `no_std` well.
2. I suggest the memories allocated by `Box::new`, please freed them by `Box::from_raw`.
3. I suggest don't not depend on the program exit to free all memories, because iced-x86 is a common base library, is not a application.

**Comment by wtfsck** [comment] 2024-04-29 02:33
This is not a memory leak since it's stored in a lazy static and statics are by definition only freed once the program exits.

My plan is to remove the lazy static dependency in a future version though.

Closing since this is not a memory leak.

**Closed by wtfsck** 2024-04-29 02:33 UTC

**Comment by persytry** [comment] 2024-04-29 04:20
Do you understand? In user mode program, it's maybe not a leaks, but in kernel mode program, it's a leaks issues.

**Comment by stevefan1999-personal** [comment] 2024-11-10 17:41
> This is not a memory leak since it's stored in a lazy static and statics are by definition only freed once the program exits.
> 
> My plan is to remove the lazy static dependency in a future version though.
> 
> Closing since this is not a memory leak.

I think he is right. It should be considered as somewhat a memory leak because you assumed there will always be an `atexit` CRT cleanup handler at the end of the program to delete all those dangling `into_raw` memories, but it is in fact not always the case if you use it in a kernel context (say like as a Linux kernel module or Windows driver) because they are never unloaded, and even if they do unload somehow, it does not call the usual CRT cleanup handlers anyway since it is in kernel and it is special.
