### ISSUE TITLE
bug: outsw memory read shows unknown size

### ISSUE THREAD

**Issue by jimstevens2001** [icedland/iced#449] opened 2023-09-01 20:46 UTC
Hello,

I found an outsw instruction in iced that is not showing a memory size for the access. I'm using this as part of a larger program that is interacting with a VM and my program blew up on a read length of 0 when decoding the size with...

size = iced_x86.MemorySizeExt.size(mem_info.memory_size)

The instruction buffer is...
0xfffff80c18656bce: 66f36f488b742408c3cccccccccccc

And here is the data that iced gives on the instruction...

iced instr is rep outsw
    OpCode: o16 6F
    Instruction: OUTSW
    Encoding: LEGACY
    Mnemonic: OUTSW
    Code: OUTSW_DX_M16                                                
    CpuidFeature: INTEL186
    FlowControl: NEXT
    RFLAGS Read: DF
    Op0Access: COND_READ
    Op1Access: COND_READ
    Op0: DX
    Op1: SEG_RSI
    Used reg: DX:COND_READ
    Used reg: RCX:READ_COND_WRITE
    Used reg: RSI:COND_READ
    Used reg: RSI:COND_WRITE
    Used mem: [DS:RSI;UNKNOWN;COND_READ]

The UNKNOWN in the last line is the issue. I think the read is supposed to be 2 bytes in this context based on the manuals and discussions with friends, but wanted to let the iced team know about this so you can address it.

**Comment by wtfsck** [comment] 2023-09-01 21:04
Yes it should be a 16-bit memory access. All instructions are tested and the the following outsw test passes:

```txt
66 6F, Outsw_DX_m16, Legacy, INTEL186, priv fr=d op0=r op1=r r=dx rw=rsi rm=ds:rsi;UInt16
```

Do you have a repro? Is it as simple as just disassembling the bytes you provided to repro this?

**Comment by jimstevens2001** [comment] 2023-09-01 21:27
Here's the minimal repro...

rnr@ritchie:/data/src/renigma-api/tests/python$ pip show iced_x86
Name: iced-x86
Version: 1.16.0
Summary: iced-x86 is a blazing fast and correct x86/x64 disassembler, assembler and instruction decoder
Home-page: https://github.com/icedland/iced/tree/master/src/rust/iced-x86-py
Author: wtfsck
Author-email: wtfsck@protonmail.com
License: MIT
Location: /data/home/rnr/.local/lib/python3.8/site-packages
Requires: 
Required-by: 

rnr@ritchie:/data/src/renigma-api/tests/python$ cat bug.py 
import binascii
import iced_x86
info_factory = iced_x86.InstructionInfoFactory()

rip = 0xfffff80c18656bce
rip_data = binascii.unhexlify("66f36f488b742408c3cccccccccccc")
decoder = iced_x86.Decoder(64, rip_data, ip=rip)

for instr in decoder:
    info = info_factory.info(instr)
    for mem_info in info.used_memory():
        size = iced_x86.MemorySizeExt.size(mem_info.memory_size)
        print(size)
    break

rnr@ritchie:/data/src/renigma-api/tests/python$ python3 bug.py 
0

**Comment by wtfsck** [comment] 2023-09-01 21:37
Thanks. This reproduces with the F3 prefix.

**Comment by wtfsck** [comment] 2023-09-01 21:49
It's returning UNKNOWN because it's a REP instruction. iced doesn't know how much memory this instruction accesses because it depends on the value of the RCX register. If RCX is 0, no memory is accessed, if it's 1, 2 bytes are accessed, and so on (in general RCX * 2 bytes are accessed). The documentation for Unknown is "Unknown size or the instruction doesn't reference any memory (eg. `LEA`)"

**Comment by wtfsck** [comment] 2023-09-01 21:53
If you want REP XXX instructions to return the same value as XXX instructions, then you can clear the REP/REPNE properties before calling the info(instr) method.

Eg.

```python
    instr.has_rep_prefix = False
    instr.has_repne_prefix = False
    info = info_factory.info(instr)
```

I'll close this since it's impossible for iced to know the actual number of bytes accessed by these REP/REPNE instructions.

**Closed by wtfsck** 2023-09-01 21:53 UTC

**Comment by jimstevens2001** [comment] 2023-09-02 08:10
Ah that makes sense. I suppose there are two ways to interpret this. If you think about the rep outsw as an atomic operation, then your interpretation makes sense because you'd need to know the dynamic state. My perspective is from a "state transformation per commit" way of thinking where a rep-style prefix works as a self GOTO with a side effect of decrementing rcx and possibly checking ZF. 

The peel the rep/repne solution works well enough and I will just add the rep prefix rcx/ZF side effects back in manually.

Thanks!

**Comment by jimstevens2001** [comment] 2023-09-07 22:11
Thanks again! Your solution worked for me as a workaround, but I thought about this a bit more and I wanted to point out something from a philosophical perspective about the semantics of disassembly that may help you with other users that using iced to interact with a live system.

Basically, the semantics of an instruction can be thought of in two ways. For most instructions, these result in the exact same thing. But with rep prefixes, you actually have two ways to think about it.

Your perspective is the total side effects of that single instruction existing in the program. In that case, you are 100% correct that the total memory range of "rep outsw" is not statically knowable because it depends on the runtime value of rcx (and also technically on the state of the page table too, since a page fault could cause that whole application to stop). 

My need is on a per commit basis. I am reading registers/memory before and after the instruction execute to get the concrete values for the inputs and outputs of the instruction. At that level of abstraction, "rep outsw" is actually more like a loop and the rep prefix basically means "while (rcx != 0) { do_the_thing(); rcx--; }" and you will see a commit for each unique rcx value when single stepping the CPU. So from that perspective, the memory usage of a single commit is statically knowable and is 2 bytes. 

Not sure if you want to change how you approach the instructions, but I wanted you to understand my logic for filing the bug report in case there are other situations that arise where the difference between the two interpretations matters. Either way, your work is incredible and I greatly appreciate it existing as a vital infrastructure for the RE world!
