### ISSUE TITLE
Underflowing subtract in decoder?

### ISSUE THREAD

**Issue by vext01** [icedland/iced#383] opened 2023-01-27 11:07 UTC
Hi,

I've been running my test suite in a loop to shake out non-deterministic bugs, and this came up:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/vext01/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-x86-1.18.0/src/decoder.rs:1480:25
```

I'm a fool because it's hard to reproduce and I wasn't running with `RUST_BACKTRACE`.

I'll try to get a backtrace...

Thanks

**Comment by wtfsck** [comment] 2023-01-27 14:39
I don't think the backtrace will help much, the input bytes would be more interesting.

**Comment by wtfsck** [comment] 2023-01-29 17:23
Is the input to the decoder the same or random?

Are you using unsafe code? Is there some thread that can overwrite the stack or is the current thread interrupted by something that could write to the stack?

**Comment by wtfsck** [comment] 2023-02-22 14:42
Have you had any success in reproducing this? I've already looked at the code and it seems impossible.

**Comment by wtfsck** [comment] 2023-02-24 15:31
I'm going to close this since I have no repro and it appears to be impossible unless someone overwrites the stack. Let me know if you do find a repro though and I'll reopen it.

**Closed by wtfsck** 2023-02-24 15:31 UTC

**Comment by jebradbury39** [comment] 2026-01-12 18:40
Just thought that I'd mention that I've also seen this error (in one of my CI runs). I don't really have any new info, unfortunately.

This is the first time I've seen it after hundreds of runs, and a re-run cleared the issue. I'm not able to get the exact bytes, either, since the CI setup wipes out the object files when it ends (the object files that I'm disassembling are test objects that I'm using bazel+clang to build).

```
thread 'main' (1522857) panicked at external/rules_rust++crate+crates__iced-x86-1.21.0/src/decoder.rs:1421:25:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not using any unsafe code directly (although I suppose it is possible that one of my dependencies might be doing something untoward). I'm only running over x86_64 ELF object files, and I'm not attempting to decode any instructions from a live process.

**Comment by jebradbury39** [comment] 2026-01-14 15:23
I guess I should have looked more closely at the other issues. Seems that this is fixed in https://github.com/icedland/iced/issues/696

The reason I still hit the issue is because I'm using the crate release of 1.21.0, which is from Jan 20, 2024 (and the fix went in May 12, 2025).
