### ISSUE TITLE
miri detects UB when running `block_enc::tests::br8_16::br8_bwd` test

### ISSUE THREAD

**Issue by lenawanel** [icedland/iced#513] opened 2024-01-28 19:35 UTC
miri complains about a stacked borrows rule violation when running the test.

command:
```bash
cargo miri test block_enc::tests::br8_16::br8_bwd 
```
in the `iced/src/rust/iced-x86` directory

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<warning about an intiger to pointer cast>

error: Undefined Behavior: trying to retag from <4069890> for SharedReadOnly permission at alloc591920[0x1], but that tag does not exist in the borrow stack for this location
    --> iced-x86/src/decoder/handlers/legacy.rs:2584:23
     |
2584 |         let this = unsafe { &*(self_ptr as *const Self) };
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |                             |
     |                             trying to retag from <4069890> for SharedReadOnly permission at alloc591920[0x1], but that tag does not exist in the borrow stack for this location
     |                             this error occurs as part of retag at alloc591920[0x0..0x8]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <4069890> was created by a SharedReadOnly retag at offsets [0x0..0x1]
    --> iced-x86/src/decoder.rs:1571:12
     |
1571 |         (decode)(handler, self, instruction);
     |                  ^^^^^^^
     = note: BACKTRACE (of the first span):
     = note: inside `decoder::handlers::legacy::OpCodeHandler_Xchg_Reg_rAX::decode` at iced-x86/src/decoder/handlers/legacy.rs:2584:23: 2584:50
note: inside `decoder::Decoder::<'_>::decode_table2`
    --> iced-x86/src/decoder.rs:1571:3
     |
1571 |         (decode)(handler, self, instruction);
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `decoder::Decoder::<'_>::decode_out_ptr`
    --> iced-x86/src/decoder.rs:1418:3
     |
1418 |         self.decode_table2(handler, instruction);
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `decoder::Decoder::<'_>::decode`
    --> iced-x86/src/decoder.rs:1314:4
     |
1314 |             self.decode_out_ptr(instruction.as_mut_ptr());
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `<decoder::DecoderIntoIter<'_> as std::iter::Iterator>::next`
    --> iced-x86/src/decoder.rs:2629:9
     |
2629 |             Some(self.decoder.decode())
     |                  ^^^^^^^^^^^^^^^^^^^^^
     = note: inside `<std::vec::Vec<instruction::Instruction> as std::vec::spec_from_iter_nested::SpecFromIterNested<instruction::Instruction, decoder::DecoderIntoIter<'_>>>::from_iter` at /home/uwu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:26:32: 26:47
     = note: inside `<std::vec::Vec<instruction::Instruction> as std::vec::spec_from_iter::SpecFromIter<instruction::Instruction, decoder::DecoderIntoIter<'_>>>::from_iter` at /home/uwu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:33:9: 33:48
     = note: inside `<std::vec::Vec<instruction::Instruction> as std::iter::FromIterator<instruction::Instruction>>::from_iter::<decoder::DecoderIntoIter<'_>>` at /home/uwu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2800:9: 2800:76
     = note: inside `<decoder::DecoderIntoIter<'_> as std::iter::Iterator>::collect::<std::vec::Vec<instruction::Instruction>>` at /home/uwu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2054:9: 2054:38
note: inside `block_enc::tests::decode`
    --> iced-x86/src/block_enc/tests/mod.rs:34:2
     |
34   |     decoder.into_iter().collect()
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `block_enc::tests::encode_test`
    --> iced-x86/src/block_enc/tests/mod.rs:54:20
     |
54   | ... = decode(bitness, orig_rip, original_data, decoder_options);
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `block_enc::tests::br8_16::br8_bwd`
    --> iced-x86/src/block_enc/tests/br8_16.rs:157:2
     |
157  | /     encode_test(
158  | |         BITNESS,
159  | |         ORIG_RIP,
160  | |         &original_data,
...    |
166  | |         &expected_reloc_infos,
167  | |     );
     | |_____^
note: inside closure
    --> iced-x86/src/block_enc/tests/br8_16.rs:91:13
     |
90   | #[test]
     | ------- in this procedural macro expansion
91   | fn br8_bwd() {
     |             ^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```

</p>
</details>

tested with 
`rustc 1.77.0-nightly (5bd5d214e 2024-01-25)`

**Comment by lenawanel** [comment] 2024-01-28 19:54
this is just the first test that will fail under miri.
lots of decoder and formatter tests fail too.

**Comment by wtfsck** [comment] 2024-01-28 20:09
Looks like a dupe of https://github.com/icedland/iced/issues/455

**Comment by wtfsck** [comment] 2024-01-28 20:11
Yes, stacktrace looks identical so I'll close this.

This is a false positive by the experimental miri stacked borrow code. See the linked issue above.

**Closed by wtfsck** 2024-01-28 20:11 UTC

**Comment by wtfsck** [comment] 2024-01-28 20:19
BTW, I plan on refactoring that part of the code to make it easier for miri, hopefully the next version, but it could take a while.
